// SAFETY ENG store model — حلول مراقبة وأمن وحضور وشاشات، مع بيانات موحدة للمتجر.
export type Product = {
  id: number; name: string; category: string; price: number; oldPrice: number; badge: string; image: string; tone: string; description: string; specs: string[]; brand?: string; stock?: number; isAvailable?: boolean; installable?: boolean; installationFee?: number;
};

export const products: Product[] = [
  { id: 1, name: "كاميرا مراقبة IP خارجية 4MP", category: "كاميرات مراقبة", price: 2499, oldPrice: 2999, badge: "الأكثر طلباً", image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=900&q=85", tone: "coral", description: "كاميرا خارجية مقاومة للعوامل الجوية برؤية ليلية واضحة، مناسبة للبيوت والمداخل والمخازن.", specs: ["دقة 4MP", "رؤية ليلية حتى 30 متر", "مقاومة للماء والغبار", "تركيب وضبط اختياري"] },
  { id: 2, name: "جهاز تسجيل NVR لـ 8 كاميرات", category: "أنظمة أمن", price: 6799, oldPrice: 7499, badge: "حل متكامل", image: "https://images.unsplash.com/photo-1558008258-3256797b43f3?auto=format&fit=crop&w=900&q=85", tone: "teal", description: "مركز تسجيل ومتابعة لنظام المراقبة مع إدارة سهلة من الموبايل وشاشة العرض.", specs: ["8 قنوات IP", "دعم مشاهدة عن بعد", "ضغط H.265", "إعداد شبكة كامل"] },
  { id: 3, name: "جهاز حضور وانصراف بالبصمة", category: "بصمة وحضور", price: 3899, oldPrice: 4499, badge: "جديد", image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=85", tone: "lime", description: "حل عملي لتسجيل حضور فريقك بالبصمة أو الوجه مع تقارير واضحة للإدارة.", specs: ["بصمة ووجه", "شاشة 3.5 بوصة", "تصدير تقارير USB", "تدريب وتشغيل"] },
  { id: 4, name: "طقم تحكم في الدخول للأبواب", category: "تحكم وأبواب", price: 3299, oldPrice: 3799, badge: "اختيارنا", image: "https://images.unsplash.com/photo-1558008258-3256797b43f3?auto=format&fit=crop&w=900&q=85", tone: "peach", description: "طقم كامل لتنظيم الدخول والخروج باستخدام كارت أو بصمة مع زر خروج وقفل كهربائي.", specs: ["قارئ كروت وبصمة", "قفل كهربائي", "زر خروج وحساس باب", "تركيب وبرمجة"] },
  { id: 5, name: "شاشة عرض 43 بوصة للمراقبة", category: "شاشات", price: 8999, oldPrice: 9999, badge: "عرض خاص", image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=85", tone: "blue", description: "شاشة واضحة لمتابعة الكاميرات وعرض التقارير في غرف الأمن والاستقبال.", specs: ["43 بوصة 4K", "مداخل HDMI متعددة", "مناسبة للتشغيل المستمر", "تثبيت جداري متاح"] },
  { id: 6, name: "طقم كاميرات 4 قنوات مع هارد", category: "كاميرات مراقبة", price: 11999, oldPrice: 13499, badge: "باكدج كامل", image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=900&q=85", tone: "yellow", description: "ابدئي نظام المراقبة من غير حيرة: أربع كاميرات، جهاز تسجيل، هارد وتركيب أساسي.", specs: ["4 كاميرات Full HD", "DVR وهارد 1TB", "مشاهدة من الموبايل", "معاينة وتركيب أساسي"] },
  { id: 7, name: "طابعة إيصالات حرارية للمكتب", category: "الطابعات والكاشير", price: 1699, oldPrice: 1999, badge: "للمكاتب", image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=900&q=85", tone: "blue", description: "طابعة عملية وسريعة للمكاتب ونقاط البيع، بحجم صغير وتشغيل بسيط.", specs: ["طباعة حرارية سريعة", "توصيل USB", "تصميم مكتبي صغير", "ضمان سنة"] },
  { id: 8, name: "لابتوب أعمال خفيف وسريع", category: "لابات وكمبيوترات", price: 24999, oldPrice: 27999, badge: "للشغل", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=85", tone: "teal", description: "لابتوب عملي لإدارة المكتب والكاشير والتقارير اليومية مع بطارية تناسب يوم العمل.", specs: ["شاشة 15.6 بوصة", "SSD سريع", "ذاكرة مناسبة للأعمال", "ضمان محلي"] },
  { id: 9, name: "طقم ماوس وكيبورد لاسلكي", category: "ماوس وكيبورد", price: 1299, oldPrice: 1599, badge: "مكتب مرتب", image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=85", tone: "lime", description: "طقم مريح وهادئ للمكاتب ونقاط البيع، بدون فوضى أسلاك على سطح المكتب.", specs: ["اتصال لاسلكي", "كيبورد عربي/إنجليزي", "ماوس مريح", "بطارية طويلة"] },
  { id: 10, name: "ماوس باد مكتبي كبير", category: "مستلزمات مكتبية", price: 249, oldPrice: 299, badge: "إضافة بسيطة", image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=85", tone: "peach", description: "باد ناعم وثابت يحسن حركة الماوس ويحافظ على ترتيب المكتب.", specs: ["سطح ناعم", "قاعدة مانعة للانزلاق", "مقاس كبير", "حواف متينة"] },
  { id: 11, name: "طقم كابلات وشواحن للمكتب", category: "كابلات وملحقات", price: 699, oldPrice: 899, badge: "أساسي", image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=85", tone: "yellow", description: "كابلات وشواحن أساسية لتجهيز المكاتب وأجهزة الكاشير والشاشات.", specs: ["USB وHDMI", "شحن سريع", "أطوال متعددة", "تنظيم أسهل"] },
  { id: 12, name: "نظام كاشير متكامل للمحل", category: "الطابعات والكاشير", price: 15999, oldPrice: 17999, badge: "باكدج كاشير", image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85", tone: "coral", description: "تجهيز عملي لنقطة البيع يشمل شاشة وكاشير وطابعة إيصالات وملحقات التشغيل.", specs: ["شاشة لمس", "طابعة إيصالات", "درج نقود", "إعداد وتشغيل"] },
  { id: 13, name: "طابعة ليزر متعددة الوظائف", category: "الطابعات والكاشير", price: 7499, oldPrice: 8299, badge: "للمكاتب", image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=900&q=85", tone: "blue", description: "طابعة ليزر للطباعة والنسخ والمسح، مناسبة للمكاتب ونقاط الخدمة.", specs: ["طباعة ونسخ ومسح", "طباعة أبيض وأسود", "اتصال Wi-Fi", "توفير في الحبر"] },
];
export function getProduct(id: string | number) { return products.find((product) => product.id === Number(id)); }
export function getInstallationFee(product: Product) { if (product.installable === false) return 0; if (product.installationFee != null) return product.installationFee; if (["كاميرات مراقبة", "بصمة وحضور", "أنظمة أمن", "تحكم وأبواب", "شاشات", "الطابعات والكاشير"].includes(product.category)) return 350; return 0; }
export function isInstallable(product: Product) { return getInstallationFee(product) > 0; }
export function getProductBrand(product: Product) { return product.brand?.trim() || "SAFETY ENG"; }
export function isInStock(product: Product) { if (product.isAvailable === false) return false; return product.stock == null || product.stock > 0; }
export function formatPrice(price: number) { return `${price.toLocaleString("ar-EG")} ج.م`; }
export function readIds(key: string): number[] { try { return JSON.parse(localStorage.getItem(key) || "[]"); } catch { return []; } }
export function saveIds(key: string, ids: number[]) { localStorage.setItem(key, JSON.stringify(ids)); }

export type CartEntry = { productId: number; quantity: number; installationRequested: boolean; installationFee: number };
export function readCartEntries(): CartEntry[] { try { const saved = JSON.parse(localStorage.getItem("safety-cart-lines") || "null"); if (Array.isArray(saved)) return saved; const ids = readIds("fluxmart-cart"); return ids.reduce<CartEntry[]>((acc, productId) => { const existing = acc.find((line) => line.productId === productId); if (existing) existing.quantity += 1; else acc.push({ productId, quantity: 1, installationRequested: false, installationFee: 0 }); return acc; }, []); } catch { return []; } }
export function saveCartEntries(entries: CartEntry[]) { localStorage.setItem("safety-cart-lines", JSON.stringify(entries)); saveIds("fluxmart-cart", entries.flatMap((line) => Array(line.quantity).fill(line.productId))); }
