// Style: ورق وبيكسل — سلة واضحة ومطمئنة بخطوات شراء قصيرة.
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { formatPrice, getProduct, products, readIds, saveIds } from "@/lib/store";

type CartLine = { id: number; quantity: number };
export default function Cart() {
  const [lines, setLines] = useState<CartLine[]>([]);
  useEffect(() => { const ids = readIds("fluxmart-cart"); const grouped = ids.reduce<CartLine[]>((acc, id) => { const line = acc.find((item) => item.id === id); if (line) line.quantity += 1; else acc.push({ id, quantity: 1 }); return acc; }, []); setLines(grouped); }, []);
  const total = useMemo(() => lines.reduce((sum, line) => sum + (getProduct(line.id)?.price || 0) * line.quantity, 0), [lines]);
  const persist = (next: CartLine[]) => { setLines(next); saveIds("fluxmart-cart", next.flatMap((line) => Array(line.quantity).fill(line.id))); };
  const change = (id: number, delta: number) => { persist(lines.map((line) => line.id === id ? { ...line, quantity: Math.max(0, line.quantity + delta) } : line).filter((line) => line.quantity)); };
  const remove = (id: number) => { persist(lines.filter((line) => line.id !== id)); toast.success("اتشال من العربة"); };
  return <div dir="rtl" className="min-h-screen bg-[#fbfaf7] text-[#172f3c]"><header className="inner-header"><div className="container flex items-center justify-between"><Link href="/" className="brand-lockup" dir="ltr"><span className="logo-mark"><img src="/manus-storage/fluxmart-mark_6d911004.png" alt="" /></span><b>Flux<span>Mart</span></b></Link><Link href="/favorites" className="icon-link">♡ المفضلة</Link></div></header><main className="container page-shell"><span className="section-kicker"><ShoppingBag size={14} /> خطوة قبل ما توصلك</span><h1>سلة مشترياتك</h1>{lines.length ? <div className="cart-layout"><div className="cart-lines">{lines.map((line) => { const product = products.find((item) => item.id === line.id); if (!product) return null; return <article className="cart-line" key={line.id}><Link href={`/product/${line.id}`} className={`cart-line-image ${product.tone}`}><img src={product.image} alt={product.name} /></Link><div className="cart-line-copy"><span>{product.category}</span><h2>{product.name}</h2><b>{formatPrice(product.price)}</b></div><div className="quantity"><button onClick={() => change(line.id, -1)}><Minus size={15} /></button><b>{line.quantity}</b><button onClick={() => change(line.id, 1)}><Plus size={15} /></button></div><button className="remove-button" onClick={() => remove(line.id)} aria-label="حذف المنتج"><Trash2 size={17} /></button></article>; })}</div><aside className="summary-card"><span>ملخص الطلب</span><h2>{formatPrice(total)}</h2><div><small>الشحن</small><b>{total >= 1500 ? "مجاني" : "50 ج.م"}</b></div><div className="summary-total"><small>الإجمالي المتوقع</small><b>{formatPrice(total + (total >= 1500 ? 0 : 50))}</b></div><Link href="/checkout" className="primary-button checkout-button">إتمام الطلب <ArrowLeft size={17} /></Link><p>الدفع عند الاستلام متاح. بياناتك في أمان.</p></aside></div> : <div className="empty-state large-empty"><ShoppingBag size={38} /><h2>العربة فاضية</h2><p>اختاري حاجاتك المفضلة وابدئي أول طلب.</p><Link href="/" className="primary-button">تصفحي المنتجات</Link></div>}</main></div>;
}
