// Style: ورق وبيكسل — سلة واضحة ومطمئنة بخطوات شراء قصيرة.
import SiteFooter from "@/components/SiteFooter";
import InnerHeader from "@/components/InnerHeader";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { formatPrice, getInstallationFee, readCartEntries, saveCartEntries, type CartEntry } from "@/lib/store";
import { useProducts } from "@/hooks/useProducts";
import { addCartItem, getCartEntriesFromApi, hasAuthToken, removeCartItem } from "@/lib/api";

type CartLine = { id: number; quantity: number };
export default function Cart() {
  const [lines, setLines] = useState<CartEntry[]>([]);
  const { products: catalogProducts } = useProducts();
  useEffect(() => { let active = true; setLines(readCartEntries()); if (hasAuthToken()) { getCartEntriesFromApi().then((remote) => { if (!active) return; const next = remote.map((item) => ({ remoteId: item.remoteId, productId: item.productId, variantId: item.variantId, quantity: item.quantity, installationRequested: false, installationFee: 0 })); setLines(next); saveCartEntries(next); }).catch(() => toast.error("تعذر تحديث السلة من الحساب، نعرض آخر نسخة محفوظة")); } return () => { active = false; }; }, []);
  const subtotal = useMemo(() => lines.reduce((sum, line) => sum + (catalogProducts.find((item) => item.id === line.productId)?.price || 0) * line.quantity, 0), [lines, catalogProducts]);
  const installationTotal = useMemo(() => lines.reduce((sum, line) => sum + (line.installationRequested ? (line.installationFee || getInstallationFee(catalogProducts.find((item) => item.id === line.productId)!)) * line.quantity : 0), 0), [lines, catalogProducts]);
  const total = subtotal + installationTotal;
  const persist = (next: CartEntry[]) => { setLines(next); saveCartEntries(next); };
  const change = async (id: number, delta: number) => { const current = lines.find((line) => line.productId === id); if (!current) return; const nextQuantity = Math.max(0, current.quantity + delta); persist(lines.map((line) => line.productId === id ? { ...line, quantity: nextQuantity } : line).filter((line) => line.quantity)); if (hasAuthToken() && current.variantId) { try { if (current.remoteId) await removeCartItem(current.remoteId); if (nextQuantity > 0) await addCartItem(current.variantId, nextQuantity); } catch { toast.error("تم تحديث السلة محليًا، لكن تعذر مزامنتها الآن"); } } };
  const remove = async (id: number) => { const current = lines.find((line) => line.productId === id); persist(lines.filter((line) => line.productId !== id)); if (hasAuthToken() && current?.remoteId) { try { await removeCartItem(current.remoteId); } catch { toast.error("تم حذف المنتج محليًا، لكن تعذر تحديث الحساب"); } } toast.success("اتشال من العربة"); };
  return <div dir="rtl" className="min-h-screen bg-[#fbfaf7] text-[#172f3c]"><InnerHeader /><main className="container page-shell"><span className="section-kicker"><ShoppingBag size={14} /> خطوة قبل ما توصلك</span><span className="paper-sticker">سلة الشراء · ٠٣</span><h1>سلة مشترياتك</h1>{lines.length ? <div className="cart-layout"><div className="cart-lines">{lines.map((line) => { const product = catalogProducts.find((item) => item.id === line.productId); if (!product) return null; return <article className="cart-line" key={`${line.productId}-${line.installationRequested}`}><Link href={`/product/${line.productId}`} className={`cart-line-image ${product.tone}`}><img src={product.image} alt={product.name} /></Link><div className="cart-line-copy"><span>{product.category}</span><h2>{product.name}</h2><b>{formatPrice(product.price)}</b>{line.installationRequested && <small className="cart-installation-line">+ تركيب: {formatPrice(line.installationFee)}</small>}</div><div className="quantity"><button onClick={() => change(line.productId, -1)}><Minus size={15} /></button><b>{line.quantity}</b><button onClick={() => change(line.productId, 1)}><Plus size={15} /></button></div><button className="remove-button" onClick={() => remove(line.productId)} aria-label="حذف المنتج"><Trash2 size={17} /></button></article>; })}</div><aside className="summary-card"><span>ملخص الطلب</span><h2>{formatPrice(total)}</h2><div><small>المنتجات</small><b>{formatPrice(subtotal)}</b></div><div><small>التركيب</small><b>{installationTotal ? formatPrice(installationTotal) : "بدون تركيب"}</b></div><div><small>الشحن</small><b>{total >= 1500 ? "مجاني" : "50 ج.م"}</b></div><div className="summary-total"><small>الإجمالي المتوقع</small><b>{formatPrice(total + (total >= 1500 ? 0 : 50))}</b></div><Link href="/checkout" className="primary-button checkout-button">إتمام الطلب <ArrowLeft size={17} /></Link><p>الدفع عند الاستلام متاح. بياناتك في أمان.</p></aside></div> : <div className="empty-state large-empty"><ShoppingBag size={38} /><h2>العربة فاضية</h2><p>اختاري حاجاتك المفضلة وابدئي أول طلب.</p><Link href="/" className="primary-button">تصفحي المنتجات</Link></div>}</main><SiteFooter /></div>;
}
