// Style: ورق وبيكسل — Checkout مطمئن، مباشر، وبحقول واضحة بدون ازدحام.
import SiteFooter from "@/components/SiteFooter";
import InnerHeader from "@/components/InnerHeader";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Check, MapPin, Phone, ShoppingBag, UserRound } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { formatPrice, getInstallationFee, getProduct, products, readCartEntries, saveCartEntries, type CartEntry } from "@/lib/store";
import { createOrder } from "@/lib/api";

export default function Checkout() {
  const [cartIds, setCartIds] = useState<CartEntry[]>([]);
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => setCartIds(readCartEntries()), []);
  const subtotal = useMemo(() => cartIds.reduce((sum, line) => sum + (getProduct(line.productId)?.price || 0) * line.quantity, 0), [cartIds]);
  const installationTotal = useMemo(() => cartIds.reduce((sum, line) => sum + (line.installationRequested ? (line.installationFee || getInstallationFee(getProduct(line.productId)!)) * line.quantity : 0), 0), [cartIds]);
  const total = subtotal + installationTotal;
  const shipping = total >= 1500 ? 0 : 50;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { form.reportValidity(); return; } const data = Object.fromEntries(new FormData(form).entries()); if (localStorage.getItem("safety-eng-token")) { try { await createOrder({ ...data, installation_fee: installationTotal, installation_requested: installationTotal > 0 }); } catch { toast.error("تم حفظ الطلب محليًا لحين تحديث API الطلبات"); } } saveCartEntries([]); setSubmitted(true); toast.success("طلبك اتأكد بنجاح"); };
  if (submitted) return <div dir="rtl" className="min-h-screen bg-[#fbfaf7] text-[#172f3c]"><main className="container success-page"><div className="success-icon"><Check size={38} /></div><span className="section-kicker">تم بحب</span><h1>طلبك في الطريق ليكي.</h1><p>شكرًا لاختيارك SAFETY ENG. هنتواصل معاكي قريبًا لتأكيد بيانات الشحن.</p><Link href="/" className="primary-button">رجوع للمتجر</Link></main><SiteFooter /></div>;
  return <div dir="rtl" className="min-h-screen bg-[#fbfaf7] text-[#172f3c]"><InnerHeader /><main className="container checkout-page"><div className="checkout-intro"><span className="section-kicker"><ShoppingBag size={14} /> آخر خطوة</span><h1>نوصّلها لحد عندك.</h1><p>اكتبي بيانات الشحن، وإحنا نكمل الباقي.</p></div><div className="checkout-layout"><form className="shipping-form" onSubmit={submit}><h2>بيانات الشحن</h2><label><UserRound size={16} /> الاسم بالكامل<input name="name" required placeholder="مثال: شهد أحمد" /></label><label><Phone size={16} /> رقم الموبايل<input name="phone" required pattern="[0-9٠-٩ +()-]{8,}" placeholder="01xxxxxxxxx" /></label><label><MapPin size={16} /> العنوان بالتفصيل<textarea name="address" required rows={3} placeholder="المحافظة، المنطقة، الشارع، رقم العقار" /></label><div className="form-row"><label>المحافظة<select name="governorate" required defaultValue=""><option value="" disabled>اختاري المحافظة</option><option>القاهرة</option><option>الجيزة</option><option>الإسكندرية</option><option>الدقهلية</option></select></label><label>طريقة الدفع<select name="payment" defaultValue="cod"><option value="cod">الدفع عند الاستلام</option><option value="card">بطاقة بنكية عند الاستلام</option></select></label></div><button type="submit" className="primary-button submit-order">تأكيد الطلب <Check size={17} /></button></form><aside className="summary-card checkout-summary"><span>ملخص سريع</span><div className="checkout-items">{cartIds.length ? cartIds.map((line) => { const product = products.find((item) => item.id === line.productId); return product ? <div key={`${line.productId}-${line.installationRequested}`}><small>{product.name} × {line.quantity}{line.installationRequested ? " + تركيب" : ""}</small><b>{formatPrice(product.price * line.quantity + (line.installationRequested ? line.installationFee * line.quantity : 0))}</b></div> : null; }) : <p>العربة فاضية، ارجعي اختاري منتج.</p>}</div><div><small>المنتجات</small><b>{formatPrice(subtotal)}</b></div><div><small>التركيب</small><b>{installationTotal ? formatPrice(installationTotal) : "بدون تركيب"}</b></div><div><small>الشحن</small><b>{shipping ? formatPrice(shipping) : "مجاني"}</b></div><div className="summary-total"><small>الإجمالي</small><b>{formatPrice(total + shipping)}</b></div></aside></div></main><SiteFooter /></div>;
}
