// Style: ورق وبيكسل — Checkout مطمئن، مباشر، وبحقول واضحة بدون ازدحام.
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Check, MapPin, Phone, ShoppingBag, UserRound } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { formatPrice, getProduct, products, readIds, saveIds } from "@/lib/store";

export default function Checkout() {
  const [cartIds, setCartIds] = useState<number[]>([]);
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => setCartIds(readIds("fluxmart-cart")), []);
  const total = useMemo(() => cartIds.reduce((sum, id) => sum + (getProduct(id)?.price || 0), 0), [cartIds]);
  const shipping = total >= 1500 ? 0 : 50;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { form.reportValidity(); return; } saveIds("fluxmart-cart", []); setSubmitted(true); toast.success("طلبك اتأكد بنجاح"); };
  if (submitted) return <div dir="rtl" className="min-h-screen bg-[#fbfaf7] text-[#172f3c]"><main className="container success-page"><div className="success-icon"><Check size={38} /></div><span className="section-kicker">تم بحب</span><h1>طلبك في الطريق ليكي.</h1><p>شكرًا لاختيارك SAFETY ENG. هنتواصل معاكي قريبًا لتأكيد بيانات الشحن.</p><Link href="/" className="primary-button">رجوع للمتجر</Link></main></div>;
  return <div dir="rtl" className="min-h-screen bg-[#fbfaf7] text-[#172f3c]"><header className="inner-header"><div className="container flex items-center justify-between"><Link href="/" className="brand-lockup" dir="ltr"><span className="logo-mark"><img src="/manus-storage/fluxmart-mark_6d911004.png" alt="" /></span><b>SAFETY<span> ENG</span></b></Link><span className="checkout-step"><Check size={15} /> بياناتك بأمان</span></div></header><main className="container checkout-page"><div className="checkout-intro"><span className="section-kicker"><ShoppingBag size={14} /> آخر خطوة</span><h1>نوصّلها لحد عندك.</h1><p>اكتبي بيانات الشحن، وإحنا نكمل الباقي.</p></div><div className="checkout-layout"><form className="shipping-form" onSubmit={submit}><h2>بيانات الشحن</h2><label><UserRound size={16} /> الاسم بالكامل<input name="name" required placeholder="مثال: شهد أحمد" /></label><label><Phone size={16} /> رقم الموبايل<input name="phone" required pattern="[0-9٠-٩ +()-]{8,}" placeholder="01xxxxxxxxx" /></label><label><MapPin size={16} /> العنوان بالتفصيل<textarea name="address" required rows={3} placeholder="المحافظة، المنطقة، الشارع، رقم العقار" /></label><div className="form-row"><label>المحافظة<select name="governorate" required defaultValue=""><option value="" disabled>اختاري المحافظة</option><option>القاهرة</option><option>الجيزة</option><option>الإسكندرية</option><option>الدقهلية</option></select></label><label>طريقة الدفع<select name="payment" defaultValue="cod"><option value="cod">الدفع عند الاستلام</option><option value="card">بطاقة بنكية عند الاستلام</option></select></label></div><button type="submit" className="primary-button submit-order">تأكيد الطلب <Check size={17} /></button></form><aside className="summary-card checkout-summary"><span>ملخص سريع</span><div className="checkout-items">{cartIds.length ? cartIds.map((id, index) => { const product = products.find((item) => item.id === id); return product ? <div key={`${id}-${index}`}><small>{product.name}</small><b>{formatPrice(product.price)}</b></div> : null; }) : <p>العربة فاضية، ارجعي اختاري منتج.</p>}</div><div><small>المنتجات</small><b>{formatPrice(total)}</b></div><div><small>الشحن</small><b>{shipping ? formatPrice(shipping) : "مجاني"}</b></div><div className="summary-total"><small>الإجمالي</small><b>{formatPrice(total + shipping)}</b></div></aside></div></main></div>;
}
