// Style: ورق وبيكسل — قائمة مفضلة خفيفة تشبه لوحة اختيارات شخصية.
import SiteFooter from "@/components/SiteFooter";
import InnerHeader from "@/components/InnerHeader";
import { useEffect, useState } from "react";
import { Heart, ShoppingBag, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { formatPrice, products, readIds, saveIds, type Product } from "@/lib/store";
import { getFavorites, hasAuthToken, normalizeProduct, removeFavoriteApi } from "@/lib/api";
import { addProductToCart } from "@/lib/cart";

export default function Favorites() {
  const [ids, setIds] = useState<number[]>([]); const [remoteProducts, setRemoteProducts] = useState<Product[]>([]); const [addingCartId, setAddingCartId] = useState<number | null>(null);
  useEffect(() => { setIds(readIds("fluxmart-favorites")); if (hasAuthToken()) getFavorites().then((payload: any) => { const raw = payload.data?.data ?? payload.data ?? []; const next = Array.isArray(raw) ? raw.map((item: any) => Number(item.product_id ?? item.product?.id ?? item.id)).filter(Boolean) : []; const fetched = Array.isArray(raw) ? raw.map((item: any, index: number) => normalizeProduct(item.product ?? item, index)) : []; setRemoteProducts(fetched); setIds(next); saveIds("fluxmart-favorites", next); }).catch(() => toast.error("تعذر تحديث المفضلة، نعرض آخر نسخة محفوظة")); }, []);
  const favoriteProducts = ids.map((id) => remoteProducts.find((product) => product.id === id) || products.find((product) => product.id === id)).filter((product): product is Product => Boolean(product));
  const remove = async (id: number) => { const previous = ids; const next = ids.filter((item) => item !== id); setIds(next); saveIds("fluxmart-favorites", next); if (hasAuthToken()) { try { await removeFavoriteApi(id); } catch { setIds(previous); saveIds("fluxmart-favorites", previous); toast.error("تعذر تحديث المفضلة على السيرفر"); return; } } toast.success("اتشال من المفضلة"); };
  const addCart = async (product: Product) => { if (addingCartId === product.id) return; setAddingCartId(product.id); try { const result = await addProductToCart(product); toast.success(`اتضاف للعربة${result.cloudSynced ? " واتحفظ في حسابك" : ""}`); } catch { toast.error("اتضاف محليًا، لكن تعذر حفظه على السيرفر"); } finally { setAddingCartId(null); } };
  return <div dir="rtl" className="min-h-screen bg-[#fbfaf7] text-[#172f3c]"><InnerHeader /><main className="container page-shell"><span className="section-kicker"><Heart size={14} /> اختياراتك المحفوظة</span><span className="paper-sticker">محفوظات · ٠٢</span><h1>قائمة المفضلة</h1><p className="page-intro">الحاجات اللي عجبِتك محفوظة هنا لحد ما تكوني جاهزة.</p>{favoriteProducts.length ? <div className="favorite-grid">{favoriteProducts.map((product) => <article className="favorite-card" key={product.id}><Link href={`/product/${product.id}`} className={`favorite-image ${product.tone}`}><img src={product.image} alt={product.name} /></Link><div><span>{product.category}</span><h2>{product.name}</h2><b className="favorite-price">{formatPrice(product.price)}</b><div className="favorite-actions"><button onClick={() => addCart(product)} disabled={addingCartId === product.id} className={`primary-button ${addingCartId === product.id ? "is-adding" : ""}`} aria-busy={addingCartId === product.id}>{addingCartId === product.id ? "جاري الحفظ..." : <>أضيفي للعربة <ShoppingBag size={15} /></>}</button><button onClick={() => remove(product.id)} className="remove-button" aria-label="إزالة من المفضلة"><Trash2 size={16} /></button></div></div></article>)}</div> : <div className="empty-state large-empty"><Heart size={38} /><h2>لسه مفيش اختيارات</h2><p>اضغطي على القلب في أي منتج عجبك وهيظهر هنا.</p><Link href="/" className="primary-button">روحي للمتجر</Link></div>}</main><SiteFooter /></div>;
}
